alpha: 0.0
max_epoch: 300
batch_size: 256
optimizer:
  name: "adam"
  kwargs:
    lr: 1e-4
    weight_decay: 0.0
patience: 300
stop_crit: "dis_loss"
norm_control:
  log_target: 0.0
  hard_every: 0
  soft_strength: 0.1
  debug: false
save: false
