max_epoch: 100
batch_size: 512
patience: 20
clean_weight: 0.2
epsilon: 0.6
attack_steps: 10
attack_step_size: null
eval_rob_freq: 5
grad_clip: 10.0
save: true
optimizer:
  name: "adam"
  kwargs:
    lr: 0.0003
    weight_decay: 0.0
