"""Analysis utilities for post-experiment analysis."""

from .wandb_fetcher import (
    WandbFetcher,
    fetch_hpo_runs,
    get_hpo_metrics_summary,
    load_local_hpo_runs,
    load_local_run,
    find_local_sweep_dirs,
)

from .mia_utils import (
    load_run_config,
    find_model_checkpoint,
)

from .statistics import (
    clean_column_name,
    compute_statistics,
    get_best_run,
    create_summary_table,
    compute_pareto_frontier,
    get_pareto_runs,
    compute_metric_correlations,
    plot_accuracy_histogram,
    plot_mean_with_std,
    plot_scatter_vs_metric,
    plot_accuracy_vs_strength,
    plot_accuracy_vs_strength_band,
    plot_pareto_frontier,
    plot_correlation_heatmap,
)

from .resolve import (
    resolve_regime_from_path,
    resolve_embedding_from_path,
    embedding_range_size,
    _EMBEDDING_RANGE_SIZE,
    resolve_params,
    resolve_metrics,
    resolve_primary_metric,
    resolve_stop_criterion,
    filter_varied_params,
    format_resolved_config,
    config_path_to_column,
    detect_robustness_eps_rel,
    detect_pretrained_info,
    normalize_param,
    get_available_params,
    get_available_regimes,
    REGIME_PARAM_MAP,
    REGIME_DESCRIPTIONS,
    REGIME_METRIC_PREFIX,
    REGIME_DEFAULT_PARAMS,
    PARAM_ALIASES,
)

__all__ = [
    # Wandb/HPO utilities
    "WandbFetcher",
    "fetch_hpo_runs",
    "get_hpo_metrics_summary",
    "load_local_hpo_runs",
    "load_local_run",
    "find_local_sweep_dirs",
    # Config loading utilities
    "load_run_config",
    "find_model_checkpoint",
    # Statistics & visualization
    "clean_column_name",
    "compute_statistics",
    "get_best_run",
    "create_summary_table",
    "compute_pareto_frontier",
    "get_pareto_runs",
    "compute_metric_correlations",
    "plot_accuracy_histogram",
    "plot_mean_with_std",
    "plot_scatter_vs_metric",
    "plot_accuracy_vs_strength",
    "plot_accuracy_vs_strength_band",
    "plot_pareto_frontier",
    "plot_correlation_heatmap",
    # HPO resolver utilities
    "resolve_regime_from_path",
    "resolve_embedding_from_path",
    "embedding_range_size",
    "_EMBEDDING_RANGE_SIZE",
    "resolve_params",
    "resolve_metrics",
    "resolve_primary_metric",
    "resolve_stop_criterion",
    "filter_varied_params",
    "format_resolved_config",
    "config_path_to_column",
    "detect_robustness_eps_rel",
    "detect_pretrained_info",
    "normalize_param",
    "get_available_params",
    "get_available_regimes",
    "REGIME_PARAM_MAP",
    "REGIME_DESCRIPTIONS",
    "REGIME_METRIC_PREFIX",
    "REGIME_DEFAULT_PARAMS",
    "PARAM_ALIASES",
]
