experiment: default
descriptor: ""

defaults:
  - _self_ # has to be here such that overrides work
  - dataset: 2Dtoy/circles
  - born: fourier/d4r3
  - trainer/nll: test
  - trainer/adversarial: null
  - tracking: test
  - override hydra/job_logging: stream_only
  - override hydra/hydra_logging: none

hydra:
  run:
    # For single runs: outputs/{dataset}/{nat|at}/{embedding}/{arch}/{kind}_{date}/
    dir: outputs/${dataset.name}/${training_regime:}/${born.embedding}/d${born.init_kwargs.in_dim}r${born.init_kwargs.bond_dim}${dtype_suffix:}/${experiment}_${now:%d%m_%H%M}

  sweep:
    # For multiruns: outputs/{dataset}/{nat|at}/{embedding}/{arch}/{kind}_{date}/{job}/
    dir: outputs/${dataset.name}/${training_regime:}/${born.embedding}/d${born.init_kwargs.in_dim}r${born.init_kwargs.bond_dim}${dtype_suffix:}/${experiment}_${now:%d%m}
    subdir: ${hydra.job.num}

  output_subdir: .hydra