project: gan_train
entity: ""  # set your W&B entity here
mode: online
seed: 42
evasion:
  method: "PGD"
  norm: 2
  criterion:
    name: "negative log-likelihood"
    kwargs:
      eps: 1e-8
  strengths: [0.1]
