project: gan_train
entity: martin-nissen-gonzalez-heidelberg-university
mode: disabled
seed: 42
evasion:
  method: "PGD"
  norm: 2
  criterion:
    name: "negative log-likelihood"
    kwargs:
      eps: 1e-8
  strengths: [0.15]
