name: "mnist_1k_r12"
gen_dow_kwargs:
  name: "mnist_1k"
  size: 100
  seed: 42
  noise: null
  circ_factor: null
  dow_link: null
  resize: 12
split: [0.7, 0.15, 0.15]
split_seed: 42
overwrite: false
scaler: linear
